<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>bsq</string>
    </array>
    <key>name</key>
    <string>Bosque</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#string-double</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#string-single</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#types</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#variables</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.bosque</string>
              </dict>
            </dict>
            <key>begin</key>
            <string>//</string>
            <key>end</key>
            <string>$</string>
            <key>name</key>
            <string>comment.line.double-dash.bosque</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.bosque</string>
              </dict>
            </dict>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.multiline.double-dash.bosque</string>
          </dict>
        </array>
      </dict>
      <key>string-double</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.bosque</string>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.bosque</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.bosque</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.bosque</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
      </dict>
      <key>string-single</key>
      <dict>
        <key>name</key>
        <string>string.quoted.single.bosque</string>
        <key>begin</key>
        <string>'</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.bosque</string>
          </dict>
        </dict>
        <key>end</key>
        <string>'</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.bosque</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.bosque</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.bosque</string>
            <key>match</key>
            <string>\b(abort|assert|case|check|elif|else|ensures|if|invariant|or|requires|return|switch|test|type|release|validate|when|where|yield)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.bosque</string>
            <key>match</key>
            <string>\b(pragma|struct|hidden|private|factory|virtual|abstract|override|entrypoint|recursive?|recursive|_debug|concept|const|enum|entity|false|field|fn|function|global|identifier|method|namespace|none|private|provides|ref|static|true|typeis|typeas|typetry|typedef|let|var)\b</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric.bosque</string>
            <key>match</key>
            <string>\b(0|[1-9][0-9]*)|(0|[1-9][0-9]*)n|([0-9]+(\.[0-9]+)?|\.[0-9]+)([eE][-+]?[0-9]+)?f\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.language</string>
            <key>match</key>
            <string>\b(none|true|false)\b</string>
          </dict>
        </array>
      </dict>
      <key>types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>entity.name.type.bosque</string>
            <key>match</key>
            <string>\b((NS[_a-zA-Z0-9]+)::(([A-MO-Z][_a-zA-Z0-9]+)|([A-Z][_a-zA-RT-Z0-9][_a-zA-Z0-9]*)))\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.name.type.bosque</string>
            <key>match</key>
            <string>\b(([A-MO-Z][_a-zA-Z0-9]+)|([A-Z][_a-zA-RT-Z0-9][_a-zA-Z0-9]*))\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.name.type.bosque</string>
            <key>match</key>
            <string>\b[A-Z]\b</string>
          </dict>
        </array>
      </dict>
      <key>variables</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>variable.name</string>
            <key>match</key>
            <string>\b(([$]?([a-z]|([a-z][_a-zA-Z0-9]*[a-zA-Z0-9])))|[_])\b</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.bsq</string>
  </dict>
</plist>